# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "geokit"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Huie"]
  s.date = "2013-08-07"
  s.description = "Geokit gem provides geocoding and distance/heading calculations"
  s.email = "david@nationbuilder.com"
  s.extensions = ["ext/mkrf_conf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "Manifest.txt",
    "README.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/mkrf_conf.rb",
    "geokit.gemspec",
    "lib/geokit.rb",
    "lib/geokit/geocoders.rb",
    "lib/geokit/inflectors.rb",
    "lib/geokit/mappable.rb",
    "lib/geokit/multi_geocoder.rb",
    "lib/geokit/services/ca_geocoder.rb",
    "lib/geokit/services/fcc.rb",
    "lib/geokit/services/geo_plugin.rb",
    "lib/geokit/services/geonames.rb",
    "lib/geokit/services/google.rb",
    "lib/geokit/services/google3.rb",
    "lib/geokit/services/ip.rb",
    "lib/geokit/services/openstreetmap.rb",
    "lib/geokit/services/us_geocoder.rb",
    "lib/geokit/services/yahoo.rb",
    "lib/geokit/version.rb",
    "test/helper.rb",
    "test/test_base_geocoder.rb",
    "test/test_bounds.rb",
    "test/test_ca_geocoder.rb",
    "test/test_geoloc.rb",
    "test/test_geoplugin_geocoder.rb",
    "test/test_google_geocoder.rb",
    "test/test_google_geocoder3.rb",
    "test/test_google_reverse_geocoder.rb",
    "test/test_inflector.rb",
    "test/test_ipgeocoder.rb",
    "test/test_latlng.rb",
    "test/test_multi_geocoder.rb",
    "test/test_multi_ip_geocoder.rb",
    "test/test_openstreetmap_geocoder.rb",
    "test/test_polygon_contains.rb",
    "test/test_us_geocoder.rb",
    "test/test_yahoo_geocoder.rb"
  ]
  s.homepage = "http://github.com/3dna/geokit"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Geokit gem provides geocoding and distance/heading calculations"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<coveralls>, [">= 0"])
      s.add_runtime_dependency(%q<mocha>, [">= 0"])
      s.add_runtime_dependency(%q<multi_json>, [">= 1.3.2"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<multi_json>, [">= 1.3.2"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<multi_json>, [">= 1.3.2"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

